(package "datetime-format"
         "0.0.1"
         "Datetime functions")

(website-url "https://github.com/zonuexe/emacs-datetime")
(keywords "datetime" "calendar")

(package-file "datetime-format.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)

(depends-on "emacs" "26.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
